### ISSUE TITLE
吾爱破解

### ISSUE THREAD

**Issue by leiyantianji** [bluesky4485/consul-dev#1]
您好，我https://www.52pojie.cn/thread-720504-1-1.html
看到您发的帖子。我不是单纯的伸手党，但是我对那2个反编译工具实在不熟。

能劳烦您把破解的文件贴出来么？感谢

再次打扰了。我的邮箱leiyantianji@163.com  leiyantianji@gmail.com

**Comment by bluesky4485** [comment]
已发gmail邮箱，请尽快查收
